name: Auto Merge Dev to Main

on:
  push:
    branches:
      - dev

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Merge dev into main
        run: |
          git fetch origin
          git checkout main
          git merge origin/dev --no-edit
          git push https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }} main
