- name: Checkout code
  uses: actions/checkout@v4

- name: Auto commit version bump
  run: |
    git config user.name "github-actions[bot]"
    git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    git pull origin main
    sed -i -E 's/<!-- version: ([0-9]+\.[0-9]+\.[0-9]+) -->/echo "<!-- version: $(date +%Y.%m.%d.%H%M) -->"/e' index.html
    git add index.html
    git commit -m "🔁 Auto-increment version" || echo "No changes to commit"
    git push origin main
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

- name: Create pull request
  uses: devops-infra/action-pull-request@v0.4.0
  with:
    github_token: ${{ secrets.PAT }}
    title: "🔁 Auto PR from Version Bump"
    target_branch: main
    source_branch: version-bump-${{ github.run_id }}

- name: Auto-merge PR
  run: |
    gh pr merge --merge --delete-branch --admin $(gh pr list --state open --head version-bump-${{ github.run_id }} --json number -q '.[0].number')
  env:
    GH_TOKEN: ${{ secrets.PAT }}
