name: Auto Version Bump

on:
  push:
    paths:
      - index.html
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # This is important for push to work

      - name: Set up Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Bump version in index.html
        shell: bash
        run: |
          FILE="index.html"
          VERSION_LINE=$(grep -Eo '<!-- version: [0-9]+\.[0-9]+\.[0-9]+ -->' "$FILE")

          if [[ $VERSION_LINE =~ ([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
            MAJOR="${BASH_REMATCH[1]}"
            MINOR="${BASH_REMATCH[2]}"
            PATCH="${BASH_REMATCH[3]}"
            NEW_PATCH=$((PATCH + 1))
            OLD="<!-- version: $MAJOR.$MINOR.$PATCH -->"
            NEW="<!-- version: $MAJOR.$MINOR.$NEW_PATCH -->"
            echo "Bumping version: $OLD → $NEW"
            sed -i "s|$OLD|$NEW|" "$FILE"
          else
            echo "❌ No version comment found in $FILE"
            exit 1
          fi

      - name: Commit and push changes
        run: |
          git add index.html
          git commit -m "🔁 Auto-increment version"
          git push
        env:
          # GITHUB_TOKEN is automatically provided by GitHub Actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
